from .dashboard import FreqTradeDashboard
from .abstract_tab import AbstractTab
from .results_analysis_tab import ResultsAnalysisTab
from .data_management_tab import DataManagementTab
from .config_editor_tab import ConfigEditorTab
from .execution_tab import ExecutionTab
from .logs_tab import LogsTab
from .hyperopt_analysis_tab import HyperoptAnalysisTab
from .backtest_analysis_tab import BacktestAnalysisTab